version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: weather-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=weatherdb
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge
